apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
  	app: db
  template:
    metadata:
  	labels:
    	app: db
    spec:
  	containers:
  	- name: db
    	image: mysql:latest
    	ports:
    	- containerPort: 3306
