apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
  	app: web
  template:
    metadata:
  	labels:
    	app: web
    spec:
  	containers:
  	- name: web
    	image: nginx:latest
    	ports:
    	- containerPort: 80
